version: '3.12'

services:
  bot:
    build:
      context: ./telegram-words-cloud-bot
      dockerfile: Dockerfile
    volumes:
      - ./data/:/app/data/
      - ./output/:/app/output/
      - ./stopwords/:/app/stopwords/
    env_file:
      - .env

volumes:
  data:
  output: